# Conexión a la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/datagrada
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
